### ISSUE TITLE
Typos and info

### ISSUE THREAD

**Issue by roysve** [JN-Husch/Portable-Receiver-Display#16]
In you file docs/gps.md there is a typo, you wrote cpgs -s it should be cgps -s.

And to use command sudo -H pip3 install gps3 --break-system-packages I had to run  python -m pip install --upgrade pip so
pip3 become version 24. seems to be minimum for this setting --break-system-packages

**Comment by JN-Husch** [comment]
Thank you for your bug report and the info regarding the pip3 version!

I adjusted the docs/gps.md.

Regarding the system packages, I will have to make some changes to install into a venv.

**Comment by JN-Husch** [comment]
Just upated the automatic installation script. It will now automatically install into a VENV, solving the need for using the --break-system-packages hack in the first place.
